import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import AuthContextProvider from '../context/AuthContext'
import { Toaster } from '@/components/ui/toaster'
import NextAuthProvider from '@/context/NextAuthProvider'
import { Navbar } from '@/components/admin-components'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <main className="p-4 bg-white h-screen">
            <div className="mx-auto max-w-5xl w-full text-sm">
              <Navbar />
              {children}
            </div>
          </main>
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  )
}
